name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y libmosquitto-dev
        sudo apt install -y libpqxx-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libjsoncpp-dev

    - name: Install Dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        choco install vcpkg --yes
        vcpkg install mosquitto:x64-windows
        vcpkg install libpqxx:x64-windows
        vcpkg install openssl:x64-windows
        vcpkg install jsoncpp:x64-windows

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20.0'  # Specify the required CMake version

    - name: Configure CMake
      run: |
        cmake -B build -S . \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ./build
      run: ctest --build-config ${{ matrix.build_type }}
